all::
	node  zebra.js
	cp /opt/apps/xmeet_new/api/xmeet.js /opt/apps/xmeet/public/v2/api/xmeet.test.js
	cp /opt/apps/xmeet_new/api/xmeet.api.css /opt/apps/xmeet/public/v2/api/xmeet.test.css

rel::
	node  zebra.js
	cp /opt/apps/xmeet_new/api/xmeet.js /opt/apps/xmeet/public/v2/api/xmeet.api.js
	cp /opt/apps/xmeet_new/api/xmeet.api.css /opt/apps/xmeet/public/v2/api/xmeet.api.css
