all::
	node  zebra.js
	cp /opt/apps/xmeet_new/api/xmeet.js /opt/apps/xmeet/public/v2/api/xmeet.test.js

rel::
	node  zebra.js
	cp /opt/apps/xmeet_new/api/xmeet.js /opt/apps/xmeet/public/v2/api/xmeet.api.js
